name: Automated Preprocessing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Execute Preprocessing Script
        run: |
          # Pindah direktori ke folder yang berisi file wine_raw.csv baru jalankan python
          cd Eksperimen_SML_Annah-Septiani
          python preprocessing/automate_Annah-Septiani.py
